use_frameworks!

platform :ios, '13.0'

target 'SixNetwork_Example' do
  pod 'SixNetwork', :path => '../'
  pod 'RxCocoa'
  pod 'SnapKit'
  
  target 'SixNetwork_Tests' do
    inherit! :search_paths

    
  end
end
