desc '自动化升级维护私有库'
lane :SpecTool do |options|

tagNum = options[:tag]
podspecName = options[:specName]

# 航道上需要执行的操作
# 具体action到 https://docs.fastlane.tools/actions 上面查找
# 这里的路径以仓库根目录为准

# 1、修改spec文件（修改s.version，s.description等）
# 2、pod install （使Example与pod下来的库产生关联）
cocoapods(
  clean: true,
  podfile: "./Example/Podfile"
)

# 3、提交本地仓库代码至远程仓库
git_add(path: ".")
git_commit(path: ".", message: "upgrade repo")
push_to_git_remote

# 4、打标签，并提交至远程
add_git_tag(
  tag: tagNum
)
push_git_tags

# 5、验证spec，并提至私有索引库
pod_lib_lint(allow_warnings: true)

# 因为本地索引库repo的名字是基本上不会去改变的，所以这里直接写死 SixSpecs
# podspec的名字需要由外界传入
pod_push(path: "#{podspecName}.podspec", repo: "SixSpecs")

end